apiVersion: mongodbatlas.crossplane.io/v1alpha2
kind: Cluster
metadata:
  name: example-cluster
spec:
  forProvider:
    projectIdRef:
      name: example-project
    providerName: TENANT
    backingProviderName: AWS
    providerRegionName: US_EAST_1
    providerInstanceSizeName: M0
  providerConfigRef:
    name: default
